// Generates database/seed.sql from the TypeScript content files, so the
// Supabase seed data and the app's local/demo content never drift apart.
// Run with: npx tsx scripts/generate-seed-sql.ts

import fs from "fs";
import path from "path";
import { MEALS } from "../content/meals";
import { WORKOUTS } from "../content/workouts";
import { WEEKS } from "../content/weeks";
import { DAYS } from "../content/days";
import { LESSONS } from "../content/lessons";
import { DAILY_TASKS } from "../content/tasks";

function esc(v: string): string {
  return v.replace(/'/g, "''");
}

const lines: string[] = [];
lines.push("-- Auto-generated by scripts/generate-seed-sql.ts — do not edit by hand.");
lines.push("-- Regenerate with: npx tsx scripts/generate-seed-sql.ts\n");

// meals
lines.push("truncate table meals restart identity cascade;");
lines.push("insert into meals (code, type, title, ingredients, portion_hint, instructions) values");
lines.push(
  Object.values(MEALS)
    .map(
      (m) =>
        `  ('${esc(m.code)}', '${esc(m.type)}', '${esc(m.title)}', ARRAY[${m.ingredients
          .map((i) => `'${esc(i)}'`)
          .join(", ")}], '${esc(m.portionHint)}', '${esc(m.instructions)}')`
    )
    .join(",\n") + ";\n"
);

// workouts + exercises
lines.push("truncate table workouts restart identity cascade;");
lines.push("truncate table workout_exercises restart identity cascade;");
lines.push("insert into workouts (code, title, location, duration_min, difficulty) values");
lines.push(
  Object.values(WORKOUTS)
    .map((w) => `  ('${esc(w.code)}', '${esc(w.title)}', '${esc(w.location)}', ${w.durationMin}, '${esc(w.difficulty)}')`)
    .join(",\n") + ";\n"
);

lines.push("insert into workout_exercises (workout_code, position, exercise_name, sets, reps, rest) values");
const exerciseRows: string[] = [];
Object.values(WORKOUTS).forEach((w) => {
  w.exercises.forEach((ex, i) => {
    exerciseRows.push(
      `  ('${esc(w.code)}', ${i + 1}, '${esc(ex.name)}', '${esc(ex.sets)}', '${esc(ex.reps)}', '${esc(ex.rest)}')`
    );
  });
});
lines.push(exerciseRows.join(",\n") + ";\n");

// weeks
lines.push("truncate table program_weeks restart identity cascade;");
lines.push("insert into program_weeks (week_number, code, title, goal) values");
lines.push(WEEKS.map((w) => `  (${w.weekNumber}, '${esc(w.code)}', '${esc(w.title)}', '${esc(w.goal)}')`).join(",\n") + ";\n");

// lessons
lines.push("truncate table lessons restart identity cascade;");
lines.push("insert into lessons (id, title, body) values");
lines.push(LESSONS.map((l) => `  ('${esc(l.id)}', '${esc(l.title)}', '${esc(l.body)}')`).join(",\n") + ";\n");

// daily tasks (content library — spec section 45 shape)
lines.push("truncate table daily_tasks restart identity cascade;");
lines.push("insert into daily_tasks (day_number, task_type, title, description) values");
lines.push(
  Object.entries(DAILY_TASKS)
    .map(([day, task]) => `  (${day}, 'habit', '${esc(task)}', null)`)
    .join(",\n") + ";\n"
);

// 56-day resolved schedule
lines.push("truncate table program_days restart identity cascade;");
lines.push(
  "insert into program_days (day_number, week_number, breakfast_code, lunch_code, snack_code, dinner_code, workout_variant, lesson_id) values"
);
lines.push(
  DAYS.map(
    (d) =>
      `  (${d.dayNumber}, ${d.weekNumber}, '${esc(d.meals.breakfast)}', '${esc(d.meals.lunch)}', '${esc(
        d.meals.snack
      )}', '${esc(d.meals.dinner)}', ${d.workoutVariant ? `'${d.workoutVariant}'` : "null"}, '${esc(d.lessonId)}')`
  ).join(",\n") + ";\n"
);

const outPath = path.join(__dirname, "..", "database", "seed.sql");
fs.writeFileSync(outPath, lines.join("\n"));
console.log(`Wrote ${outPath}`);
